import React, { createContext, useContext, useState, useCallback, useEffect } from 'react';

const LanguageContext = createContext();

export const useLanguage = () => {
  const context = useContext(LanguageContext);
  if (!context) throw new Error('useLanguage must be used within LanguageProvider');
  return context;
};

const translations = {
  en: {
    appName: 'Smart Queue',
    appSubtitle: 'University Queue Management System',
    welcome: 'Welcome',
    login: 'Login',
    signup: 'Sign Up',
    logout: 'Logout',
    email: 'Email',
    password: 'Password',
    confirmPassword: 'Confirm Password',
    studentId: 'Student ID',
    firstName: 'First Name',
    lastName: 'Last Name',
    phone: 'Phone Number',
    optional: 'Optional',
    required: 'Required',
    submit: 'Submit',
    cancel: 'Cancel',
    confirm: 'Confirm',
    delete: 'Delete',
    edit: 'Edit',
    save: 'Save',
    back: 'Back',
    next: 'Next',
    search: 'Search',
    filter: 'Filter',
    sort: 'Sort',
    loading: 'Loading...',
    noData: 'No data available',
    error: 'Error',
    success: 'Success',
    warning: 'Warning',
    info: 'Information',
    haveAccount: 'Already have an account?',
    noAccount: 'Do not have an account?',
    loginHere: 'Login here',
    signupHere: 'Sign up here',
    forgotPassword: 'Forgot Password?',
    rememberMe: 'Remember me',
    studentLogin: 'Student Login',
    studentSignup: 'Student Registration',
    enterStudentId: 'Enter your student ID',
    enterPassword: 'Enter your password',
    createPassword: 'Create a password',
    confirmYourPassword: 'Confirm your password',
    enterEmail: 'Enter your university email',
    enterPhone: 'Enter your phone number (optional)',
    enterFirstName: 'Enter your first name',
    enterLastName: 'Enter your last name',
    selectIssue: 'Select Issue Type',
    issueTypes: 'Issue Types',
    admission: 'Admission',
    financial: 'Financial',
    academic: 'Academic',
    itSupport: 'IT Support',
    studentAffairs: 'Student Affairs',
    other: 'Other',
    staffInfo: 'Staff Information',
    staffName: 'Staff Name',
    roomNumber: 'Room Number',
    block: 'Block',
    floor: 'Floor',
    queueStatus: 'Queue Status',
    yourPosition: 'Your Position',
    peopleBefore: 'People Before You',
    studentsBefore: 'Students Before',
    parentsBefore: 'Parents Before',
    estimatedWait: 'Estimated Wait Time',
    minutes: 'minutes',
    currentQueue: 'Current Queue',
    confirmQueue: 'Confirm Queue',
    cancelQueue: 'Cancel Queue',
    queueConfirmed: 'Queue Confirmed!',
    queueCancelled: 'Queue Cancelled',
    ticketNumber: 'Ticket Number',
    yourTurn: 'Your Turn Now!',
    turnAfter3Min: 'Your turn is in 3 minutes',
    turnNotification: 'Turn Notification',
    notifications: 'Notifications',
    noNotifications: 'No notifications',
    markAllRead: 'Mark all as read',
    parentPriority: 'Parent Priority',
    studentPriority: 'Student Priority',
    priorityEnabled: 'Priority queue enabled for parents',
    dashboard: 'Dashboard',
    myAppointments: 'My Appointments',
    activeAppointment: 'Active Appointment',
    queueHistory: 'Queue History',
    statistics: 'Statistics',
    profile: 'Profile',
    settings: 'Settings',
    totalVisits: 'Total Visits',
    completed: 'Completed',
    averageWait: 'Average Wait Time',
    waiting: 'Waiting',
    serving: 'Serving',
    served: 'Served',
    cancelled: 'Cancelled',
    paused: 'Paused',
    noShow: 'No Show',
    viewDetails: 'View Details',
    refresh: 'Refresh',
    download: 'Download',
    export: 'Export',
    print: 'Print',
    poweredBy: 'Powered by Smart Queue',
    version: 'Version 2.0',
    invalidCredentials: 'Invalid credentials',
    passwordMismatch: 'Passwords do not match',
    emailExists: 'Email already exists',
    idExists: 'Student ID already exists',
    queueFull: 'Queue is full',
    staffUnavailable: 'Staff is unavailable',
    alreadyInQueue: 'You are already in queue',
    voiceInput: 'Voice Input',
    listening: 'Listening...',
    speakNow: 'Speak now',
    scanQR: 'Scan QR Code',
    showQR: 'Show QR Code',
    language: 'Language',
    english: 'English',
    arabic: 'Arabic',
  },
  ar: {
    appName: 'الطابور الذكي',
    appSubtitle: 'نظام إدارة الطابور الجامعي',
    welcome: 'مرحباً',
    login: 'تسجيل الدخول',
    signup: 'إنشاء حساب',
    logout: 'تسجيل الخروج',
    email: 'البريد الإلكتروني',
    password: 'كلمة المرور',
    confirmPassword: 'تأكيد كلمة المرور',
    studentId: 'رقم الطالب',
    firstName: 'الاسم الأول',
    lastName: 'الاسم الأخير',
    phone: 'رقم الهاتف',
    optional: 'اختياري',
    required: 'مطلوب',
    submit: 'إرسال',
    cancel: 'إلغاء',
    confirm: 'تأكيد',
    delete: 'حذف',
    edit: 'تعديل',
    save: 'حفظ',
    back: 'رجوع',
    next: 'التالي',
    search: 'بحث',
    filter: 'تصفية',
    sort: 'ترتيب',
    loading: 'جاري التحميل...',
    noData: 'لا توجد بيانات',
    error: 'خطأ',
    success: 'نجاح',
    warning: 'تحذير',
    info: 'معلومات',
    haveAccount: 'لديك حساب بالفعل؟',
    noAccount: 'ليس لديك حساب؟',
    loginHere: 'سجل الدخول هنا',
    signupHere: 'سجل هنا',
    forgotPassword: 'نسيت كلمة المرور؟',
    rememberMe: 'تذكرني',
    studentLogin: 'تسجيل دخول الطالب',
    studentSignup: 'تسجيل الطالب',
    enterStudentId: 'أدخل رقم الطالب',
    enterPassword: 'أدخل كلمة المرور',
    createPassword: 'أنشئ كلمة مرور',
    confirmYourPassword: 'أكد كلمة المرور',
    enterEmail: 'أدخل بريدك الجامعي',
    enterPhone: 'أدخل رقم هاتفك (اختياري)',
    enterFirstName: 'أدخل اسمك الأول',
    enterLastName: 'أدخل اسمك الأخير',
    selectIssue: 'اختر نوع المشكلة',
    issueTypes: 'أنواع المشاكل',
    admission: 'القبول',
    financial: 'المالية',
    academic: 'الأكاديمية',
    itSupport: 'دعم تقني',
    studentAffairs: 'شؤون الطلاب',
    other: 'أخرى',
    staffInfo: 'معلومات الموظف',
    staffName: 'اسم الموظف',
    roomNumber: 'رقم الغرفة',
    block: 'المبنى',
    floor: 'الطابق',
    queueStatus: 'حالة الطابور',
    yourPosition: 'موقعك',
    peopleBefore: 'الأشخاص قبلك',
    studentsBefore: 'الطلاب قبلك',
    parentsBefore: 'الأولياء قبلك',
    estimatedWait: 'وقت الانتظار المتوقع',
    minutes: 'دقيقة',
    currentQueue: 'الطابور الحالي',
    confirmQueue: 'تأكيد الطابور',
    cancelQueue: 'إلغاء الطابور',
    queueConfirmed: 'تم تأكيد الطابور!',
    queueCancelled: 'تم إلغاء الطابور',
    ticketNumber: 'رقم التذكرة',
    yourTurn: 'دورك الآن!',
    turnAfter3Min: 'دورك بعد 3 دقائق',
    turnNotification: 'إشعار الدور',
    notifications: 'الإشعارات',
    noNotifications: 'لا توجد إشعارات',
    markAllRead: 'تحديد الكل كمقروء',
    parentPriority: 'أولوية الوالدين',
    studentPriority: 'أولوية الطالب',
    priorityEnabled: 'الأولوية مفعلة للوالدين',
    dashboard: 'لوحة التحكم',
    myAppointments: 'مواعيدي',
    activeAppointment: 'الموعد النشط',
    queueHistory: 'سجل الطابور',
    statistics: 'الإحصائيات',
    profile: 'الملف الشخصي',
    settings: 'الإعدادات',
    totalVisits: 'إجمالي الزيارات',
    completed: 'مكتمل',
    averageWait: 'متوسط وقت الانتظار',
    waiting: 'في الانتظار',
    serving: 'جاري الخدمة',
    served: 'تمت الخدمة',
    cancelled: 'ملغى',
    paused: 'متوقف',
    noShow: 'لم يحضر',
    viewDetails: 'عرض التفاصيل',
    refresh: 'تحديث',
    download: 'تحميل',
    export: 'تصدير',
    print: 'طباعة',
    poweredBy: 'مدعوم من الطابور الذكي',
    version: 'الإصدار 2.0',
    invalidCredentials: 'بيانات غير صحيحة',
    passwordMismatch: 'كلمات المرور غير متطابقة',
    emailExists: 'البريد الإلكتروني موجود مسبقاً',
    idExists: 'رقم الطالب موجود مسبقاً',
    queueFull: 'الطابور ممتلئ',
    staffUnavailable: 'الموظف غير متاح',
    alreadyInQueue: 'أنت في الطابور بالفعل',
    voiceInput: 'الإدخال الصوتي',
    listening: 'جاري الاستماع...',
    speakNow: 'تكلم الآن',
    scanQR: 'مسح رمز QR',
    showQR: 'عرض رمز QR',
    language: 'اللغة',
    english: 'English',
    arabic: 'العربية',
  }
};

export const LanguageProvider = ({ children }) => {
  const [lang, setLang] = useState(() => {
    const saved = localStorage.getItem('language');
    return saved || 'en';
  });

  const t = useCallback((key) => {
    return translations[lang][key] || key;
  }, [lang]);

  const toggleLanguage = useCallback(() => {
    const newLang = lang === 'en' ? 'ar' : 'en';
    setLang(newLang);
    localStorage.setItem('language', newLang);
    document.documentElement.dir = newLang === 'ar' ? 'rtl' : 'ltr';
    document.documentElement.lang = newLang;
  }, [lang]);

  const setLanguage = useCallback((newLang) => {
    setLang(newLang);
    localStorage.setItem('language', newLang);
    document.documentElement.dir = newLang === 'ar' ? 'rtl' : 'ltr';
    document.documentElement.lang = newLang;
  }, []);

  useEffect(() => {
    document.documentElement.dir = lang === 'ar' ? 'rtl' : 'ltr';
    document.documentElement.lang = lang;
  }, [lang]);

  const value = {
    lang,
    t,
    toggleLanguage,
    setLanguage,
    isRTL: lang === 'ar',
  };

  return <LanguageContext.Provider value={value}>{children}</LanguageContext.Provider>;
};

export default LanguageContext;